### ISSUE TITLE
No module named 'sos_papermill'

### ISSUE THREAD

**Issue by sonnylaskar** [vatlab/sos-papermill#2]
Hi,

I installed the package as `pip3 install sos-papermill`
But on running papermill, it can't find it:
```
$ papermill --engine sos U1.ipynb U1_o.ipynb
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/papermill", line 7, in <module>
    from papermill.cli import papermill
  File "/home/ubuntu/.local/lib/python3.6/site-packages/papermill/__init__.py", line 6, in <module>
    from .execute import execute_notebook
  File "/home/ubuntu/.local/lib/python3.6/site-packages/papermill/execute.py", line 11, in <module>
    from .engines import papermill_engines
  File "/home/ubuntu/.local/lib/python3.6/site-packages/papermill/engines.py", line 373, in <module>
    papermill_engines.register_entry_points()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/papermill/engines.py", line 38, in register_entry_points
    self.register(entrypoint.name, entrypoint.load())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'sos_papermill'
```

I can see the package in Python3 but cant import anything:
```
$ python3
Python 3.6.8 (default, Aug 20 2019, 17:12:48)
[GCC 8.3.0] on linux
>>> import sos_papermill
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sos_papermill'
>>> import pip
>>> sorted(["%s==%s" % (i.key, i.version) for i in pip.get_installed_distributions()])
['ansiwrap==0.8.4', 'attrs==19.1.0', 'backcall==0.1.0', 'bash-kernel==0.7.1', 'beautifulsoup4==4.8.0', 'bleach==3.1.0', 'bs4==0.0.1', 'certifi==2019.9.11', 'chardet==3.0.4', 'click==7.0', 'decorator==4.4.0', 'defusedxml==0.6.0', 'entrypoints==0.3', 'fasteners==0.15', 'feather-format==0.4.0', 'future==0.17.1', 'idna==2.8', 'ipykernel==5.1.2', 'ipython-genutils==0.2.0', 'ipython==7.8.0', 'jedi==0.15.1', 'jinja2==2.10.1', 'jsonschema==3.0.2', 'jupyter-client==5.3.2', 'jupyter-core==4.5.0', 'markupsafe==1.1.1', 'mistune==0.8.4', 'monotonic==1.5', 'nbconvert==5.6.0', 'nbformat==4.4.0', 'networkx==2.3', 'notebook==6.0.1', 'numpy==1.17.2', 'pandas==0.25.1', 'pandocfilters==1.4.2', 'papermill==1.1.0', 'parso==0.5.1', 'pexpect==4.7.0', 'pickleshare==0.7.5', 'prometheus-client==0.7.1', 'prompt-toolkit==2.0.9', 'psutil==5.6.3', 'ptyprocess==0.6.0', 'pyarrow==0.14.1', 'pydot==1.4.1', 'pydotplus==2.0.2', 'pygments==2.4.2', 'pyparsing==2.4.2', 'pyrsistent==0.15.4', 'python-dateutil==2.8.0', 'pytz==2019.2', 'pyyaml==5.1.2', 'pyzmq==18.1.0', 'requests==2.22.0', 'send2trash==1.5.0', 'setuptools==41.2.0', 'six==1.12.0', 'sos-bash==0.19.0', 'sos-javascript==0.18.0', 'sos-notebook==0.20.2', 'sos-papermill==0.1.0', 'sos-python==0.18.2', 'sos-r==0.19.1', 'sos==0.20.1', 'soupsieve==1.9.3', 'tabulate==0.8.3', 'tenacity==5.1.1', 'terminado==0.8.2', 'testpath==0.4.2', 'textwrap3==0.9.2', 'tornado==6.0.3', 'tqdm==4.35.0', 'traitlets==4.3.2', 'urllib3==1.25.3', 'wcwidth==0.1.7', 'webencodings==0.5.1', 'xxhash==1.4.1']


```

**Comment by BoPeng** [comment]
Missing a `__init__.py` in the package, please upgrade.

**Comment by sonnylaskar** [comment]
Thanks , this solved the issue.
